#!/usr/bin/env bash
# branch-name.sh — the single source of truth for what a branch name in this suite MEANS.
#
# Sourced, never executed. Consumers: lib/branches.sh, lib/backlog-preflight.sh,
# lib/backlog-teardown.sh. All three are invoked as `bash /abs/path/…`, which matters: the
# Bash tool runs the user's LOGIN SHELL (zsh), where `[[ =~ ]]` captures land in `$match`, not
# `BASH_REMATCH`. Nothing here may be pasted into a ```bash fence in a SKILL.md.
#
# THE GRAMMAR — Conventional Commits types as branch prefixes:
#
#   {type}[({scope})][!]/[{issue}-]{slug}
#
# Four facts decided the shape, each verified against a real repo rather than assumed:
#
#   1. `git for-each-ref` wildcards DO NOT CROSS `/`. With `feat/42-a/b` on disk, both
#      `refs/heads/*/42-*` and `refs/heads/**/42-*` return nothing for it. A slug of `.+`
#      would therefore mint branches that preflight guard 6 and teardown cannot see — the
#      branch exists, the scan reports clean, and /work cuts a second branch for the issue.
#      Hence the slug is [A-Za-z0-9._-]+ and a slug containing `/` is UNRECOGNIZED.
#
#   2. zsh glob-expands `(` `)`. An unquoted `feat(api)/42-x` is rc=1, "no matches found".
#      That is a runtime failure `zsh -n` cannot see, so every {branch} placeholder in the
#      skills is quoted and tests/skill-blocks-portability.sh has a check that keeps it that
#      way. Scopes are ACCEPTED here but never GENERATED by /work or /backlog.
#
#   3. `feature` is FIRST in the alternation. ERE is leftmost-longest so `feature/42-x` would
#      resolve correctly anyway, but a future reimplementation as a `case` prefix test would
#      silently call it type `feat`. Ordering makes both spellings right. Pinned by a test.
#
#   4. The issue segment is INHERENTLY AMBIGUOUS: `fix/2024-01-migration` parses as issue
#      #2024 and there is no regex that fixes it. Callers MUST treat bn_issue as a candidate
#      and degrade to issue-less mode when `gh issue view` cannot confirm it — never write
#      `Closes #2024` on the strength of the branch name alone.
#
# `feature` is legacy: accepted forever so live branches and open PRs keep working, never
# generated. Nothing is renamed by this change.

# Ordered; `feature` first (fact 3). /work and /backlog generate from the tail of this list.
BRANCH_TYPES="feature feat fix docs style refactor perf test build ci chore revert"

_BRANCH_RE='^(feature|feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(([A-Za-z0-9._-]+)\))?(!)?/(([0-9]+)-)?([A-Za-z0-9._-]+)$'

# branch_parse <name> -> rc 0 if recognized, 1 otherwise.
# Always sets all five outputs, empty on a miss: an unset variable under `set -u` in a consumer
# is a crash, and lib/branches.sh may never exit non-zero.
branch_parse() {
  bn_type=""; bn_scope=""; bn_breaking=""; bn_issue=""; bn_slug=""
  [ -n "${1:-}" ] || return 1
  [[ "$1" =~ $_BRANCH_RE ]] || return 1
  bn_type="${BASH_REMATCH[1]}"
  bn_scope="${BASH_REMATCH[3]}"
  bn_breaking="${BASH_REMATCH[4]}"
  bn_issue="${BASH_REMATCH[6]}"
  bn_slug="${BASH_REMATCH[7]}"
  # Strip leading zeros: GitHub does not link `Closes #007`. `10#` forces base 10 so `010`
  # is 10 and not an octal parse error.
  [ -n "$bn_issue" ] && bn_issue=$((10#$bn_issue))
  return 0
}

# branch_refs_strict <repo_dir> <issue> — local branches for this issue that the grammar
# RECOGNIZES. Enumerates refs/heads and filters in-process rather than passing a pattern to
# for-each-ref: wildmatch semantics (fact 1) are exactly what must not sit on a correctness
# path that feeds `git branch -D`.
branch_refs_strict() {
  local dir="$1" issue="$2" ref
  while IFS= read -r ref; do
    [ -n "$ref" ] || continue
    branch_parse "$ref" || continue
    [ "$bn_issue" = "$issue" ] && printf '%s\n' "$ref"
  done <<STRICT
$(git -C "$dir" for-each-ref --format='%(refname:short)' refs/heads 2>/dev/null)
STRICT
}

# branch_refs_issue_shaped <repo_dir> <issue> — ANY local branch with a `/`-component that
# begins `{issue}-`, recognized or not.
#
# Deliberately BROADER than branch_refs_strict, and the asymmetry is the point. This feeds
# preflight guard 6, which REFUSES: a false stop on `travis/42-notes` costs one clear error
# message, while a missed `feat/42-a/b` costs a duplicate branch and a run that reports clean.
# Never use this to decide a deletion.
branch_refs_issue_shaped() {
  local dir="$1" issue="$2" ref tail
  while IFS= read -r ref; do
    [ -n "$ref" ] || continue
    case "$ref" in */*) tail="${ref#*/}" ;; *) continue ;; esac
    case "$tail" in "$issue"-*) printf '%s\n' "$ref" ;; esac
  done <<SHAPED
$(git -C "$dir" for-each-ref --format='%(refname:short)' refs/heads 2>/dev/null)
SHAPED
}

# branch_type_for_labels <label>... — the conventional type an issue's labels imply.
# ORDERED, first match wins, and the order is part of the contract: /work derives this inline
# while /backlog derives it in the orchestrator, so an unspecified order would branch an issue
# labelled both `bug` and `documentation` differently depending on which command ran.
# No ${v,,}: bash-only, and banned by the portability lint.
branch_type_for_labels() {
  local l norm
  for l in "$@"; do
    norm=$(printf '%s' "$l" | tr 'A-Z' 'a-z')
    case "$norm" in bug|defect|regression) echo fix; return 0 ;; esac
  done
  for l in "$@"; do
    norm=$(printf '%s' "$l" | tr 'A-Z' 'a-z')
    case "$norm" in
      documentation|docs)      echo docs;     return 0 ;;
      performance|perf)        echo perf;     return 0 ;;
      refactor|refactoring)    echo refactor; return 0 ;;
      test|tests|testing)      echo test;     return 0 ;;
      ci|build)                echo ci;       return 0 ;;
      chore|dependencies|deps) echo chore;    return 0 ;;
    esac
  done
  # Default. Note only `bug`, `documentation` and `enhancement` are GitHub DEFAULT labels, so
  # in most repos this map degrades to `feat` — that is correct, not broken.
  echo feat
}
